<?php

use App\Http\Controllers\ExternalApi\AreasController;
use App\Http\Controllers\ExternalApi\AutomatedCommentaryController;
use App\Http\Controllers\ExternalApi\BasicMatchStatsController;
use App\Http\Controllers\ExternalApi\ContestantParticipationController;
use App\Http\Controllers\ExternalApi\DeletionsController;
use App\Http\Controllers\ExternalApi\DetailedMatchStatsController;
use App\Http\Controllers\ExternalApi\FixturesLiveScoresResultsController;
use App\Http\Controllers\ExternalApi\FixturesResultsController;
use App\Http\Controllers\ExternalApi\MatchEventsController;
use App\Http\Controllers\ExternalApi\MatchPreviewController;
use App\Http\Controllers\ExternalApi\PassMatrixAverageFormationController;
use App\Http\Controllers\ExternalApi\PenaltiesController;
use App\Http\Controllers\ExternalApi\PlayerCareerController;
use App\Http\Controllers\ExternalApi\PlayerContractController;
use App\Http\Controllers\ExternalApi\PossessionsController;
use App\Http\Controllers\ExternalApi\RankingsController;
use App\Http\Controllers\ExternalApi\RefreesController;
use App\Http\Controllers\ExternalApi\SeasonStatsController;
use App\Http\Controllers\ExternalApi\SquadsController;
use App\Http\Controllers\ExternalApi\StandingsController;
use App\Http\Controllers\ExternalApi\TeamsController;
use App\Http\Controllers\ExternalApi\TournamentCalendarController;
use App\Http\Controllers\ExternalApi\TournamentScheduleController;
use App\Http\Controllers\ExternalApi\TransfersController;
use App\Http\Controllers\ExternalApi\TrophiesController;
use App\Http\Controllers\ExternalApi\VenuesController;

Route::get('/external-api/areas', [AreasController::class, 'getAreas']);
Route::get('/external-api/automated-commentary', [AutomatedCommentaryController::class, 'getAutomatedCommentary']);
Route::get('/external-api/basic-match-stats', [BasicMatchStatsController::class, 'getBasicMatchStats']);
Route::get('/external-api/contestant-participation', [ContestantParticipationController::class, 'getContestantParticipation']);
Route::get('/external-api/deletions', [DeletionsController::class, 'getDeletions']);
Route::get('/external-api/detailed-matchStats', [DetailedMatchStatsController::class, 'getDetailedMatchStats']);
Route::get('/external-api/fixtures-live-scores-results', [FixturesLiveScoresResultsController::class, 'getFixturesLiveScoresResults']);
Route::get('/external-api/fixtures-results', [FixturesResultsController::class, 'getFixturesResults']);
Route::get('/external-api/match-events', [MatchEventsController::class, 'getMatchEvents']);
Route::get('/external-api/match-preview', [MatchPreviewController::class, 'getMatchPreview']);
Route::get('/external-api/pass-matrix-average-formation', [PassMatrixAverageFormationController::class, 'getPassMatrixAverageFormation']);
Route::get('/external-api/penalties', [PenaltiesController::class, 'getPenalties']);
Route::get('/external-api/player-career', [PlayerCareerController::class, 'getPlayerCareer']);
Route::get('/external-api/player-contract', [PlayerContractController::class, 'getPlayerContract']);
Route::get('/external-api/possessions', [PossessionsController::class, 'getPossessions']);
Route::get('/external-api/rankings', [RankingsController::class, 'getRankings']);
Route::get('/external-api/refrees', [RefreesController::class, 'getRefrees']);
Route::get('/external-api/season-stats', [SeasonStatsController::class, 'getSeasonStats']);
Route::get('/external-api/squads', [SquadsController::class, 'getSquads']);
Route::get('/external-api/standings', [StandingsController::class, 'getStandings']);
Route::get('/external-api/teams', [TeamsController::class, 'getTeams']);
Route::get('/external-api/tournament-calendar', [TournamentCalendarController::class, 'getTournamentCalendar']);
Route::get('/external-api/tournament-schedule', [TournamentScheduleController::class, 'getTournamentSchedule']);
Route::get('/external-api/transfers', [TransfersController::class, 'getTransfers']);
Route::get('/external-api/trophies', [TrophiesController::class, 'getTrophies']);
Route::get('/external-api/venues', [VenuesController::class, 'getVenues']);