<?php

use App\Http\Controllers\ExternalApi\AreasController;
use App\Http\Controllers\ExternalApi\AutomatedCommentaryController;
use App\Http\Controllers\ExternalApi\BasicMatchStatsController;
use App\Http\Controllers\ExternalApi\ContestantParticipationController;
use App\Http\Controllers\ExternalApi\DeletionsController;
use App\Http\Controllers\ExternalApi\DetailedMatchStatsController;
use App\Http\Controllers\ExternalApi\FixturesLiveScoresResultsController;
use App\Http\Controllers\ExternalApi\FixturesResultsController;
use App\Http\Controllers\ExternalApi\MatchEventsController;
use App\Http\Controllers\ExternalApi\MatchPreviewController;
use App\Http\Controllers\ExternalApi\PassMatrixAverageFormationController;
use App\Http\Controllers\ExternalApi\PenaltiesController;
use App\Http\Controllers\ExternalApi\PlayerCareerController;
use App\Http\Controllers\ExternalApi\PlayerContractController;
use App\Http\Controllers\ExternalApi\PossessionsController;
use App\Http\Controllers\ExternalApi\RankingsController;
use App\Http\Controllers\ExternalApi\RefreesController;
use App\Http\Controllers\ExternalApi\SeasonStatsController;
use App\Http\Controllers\ExternalApi\SquadsController;
use App\Http\Controllers\ExternalApi\StandingsController;
use App\Http\Controllers\ExternalApi\TeamsController;
use App\Http\Controllers\ExternalApi\TournamentCalendarController;
use App\Http\Controllers\ExternalApi\TournamentScheduleController;
use App\Http\Controllers\ExternalApi\TransfersController;
use App\Http\Controllers\ExternalApi\TrophiesController;
use App\Http\Controllers\ExternalApi\VenuesController;

Route::get('/external-api/areas', [AreasController::class, 'getAreas']);
Route::get('/external-api/automated-commentary/{fixtureUuid}', [AutomatedCommentaryController::class, 'getAutomatedCommentary']);
Route::get('/external-api/basic-match-stats/{fixtureUuid}', [BasicMatchStatsController::class, 'getBasicMatchStats']);
Route::get('/external-api/contestant-participation/{contestantUUID}', [ContestantParticipationController::class, 'getContestantParticipation']);
Route::get('/external-api/deletions', [DeletionsController::class, 'getDeletions']);
Route::get('/external-api/detailed-matchStats/{fixtureUuid}', [DetailedMatchStatsController::class, 'getDetailedMatchStats']);
Route::get('/external-api/fixtures-live-scores-results/{tournamentCalendarUuid}', [FixturesLiveScoresResultsController::class, 'getFixturesLiveScoresResults']);
Route::get('/external-api/fixtures-results/{tournamentCalendarUuid}', [FixturesResultsController::class, 'getFixturesResults']);
Route::get('/external-api/match-events/{fixtureUuid}', [MatchEventsController::class, 'getMatchEvents']);
Route::get('/external-api/match-preview/{fixtureUuid}', [MatchPreviewController::class, 'getMatchPreview']);
Route::get('/external-api/pass-matrix-average-formation/{fixtureUuid}', [PassMatrixAverageFormationController::class, 'getPassMatrixAverageFormation']);
Route::get('/external-api/penalties/{fixtureUuid}', [PenaltiesController::class, 'getPenalties']);
Route::get('/external-api/player-career/{personUuid}', [PlayerCareerController::class, 'getPlayerCareer']);
Route::get('/external-api/player-contract/{personUuid}', [PlayerContractController::class, 'getPlayerContract']);
Route::get('/external-api/possessions/{fixtureUuid}', [PossessionsController::class, 'getPossessions']);
Route::get('/external-api/rankings/{tournamentCalendarUuid}', [RankingsController::class, 'getRankings']);
Route::get('/external-api/refrees/{tournamentCalendarUuid}', [RefreesController::class, 'getRefrees']);
Route::get('/external-api/season-stats/{tournamentCalendarUuid}/{contestantUUID}', [SeasonStatsController::class, 'getSeasonStats']);
Route::get('/external-api/squads/{tournamentCalendarUuid}', [SquadsController::class, 'getSquads']);
Route::get('/external-api/standings/{tournamentCalendarUuid}', [StandingsController::class, 'getStandings']);
Route::get('/external-api/teams/{tournamentCalendarUuid}', [TeamsController::class, 'getTeams']);
Route::get('/external-api/tournament-calendar', [TournamentCalendarController::class, 'getTournamentCalendar']);
Route::get('/external-api/tournament-schedule/{tournamentCalendarUuid}', [TournamentScheduleController::class, 'getTournamentSchedule']);
Route::get('/external-api/transfers/{tournamentCalendarUuid}', [TransfersController::class, 'getTransfers']);
Route::get('/external-api/trophies/{contestantUUID}', [TrophiesController::class, 'getTrophies']);
Route::get('/external-api/venues/{tournamentCalendarUuid}', [VenuesController::class, 'getVenues']);